### ISSUE TITLE
Reduce size of doc directory

### ISSUE THREAD

**Issue by pwep** [dpc10ster/RJafroc#13]
As mentioned in [this card on the project board](https://github.com/dpc10ster/RJafroc/projects/1#card-23097991), a NOTE is generated about directory sizes when the package is checked or built.

The `doc` directory is automatically created and filled with the vignette output (see [this image](http://r-pkgs.had.co.nz/diagrams/package-files.png) from <http://r-pkgs.had.co.nz/package.html>.

There might be scope to optimise the file size of images in `vignettes/images` using a tool called `pngcrush`.

**Comment by dpc10ster** [comment]
- Thanks for looking into this. I will look into your proposed fix.

- But that leaves the question of what to do, long term, with `vignettes`. My goal is to convert _all_ of the code in my book to `vignettes` as, in my opinion, that is the best way of conveying the ideas. But that would lead to a much larger file size in `doc`. One idea: separate website using `pkgdown::build-site`.
