### ISSUE TITLE
Travis builds

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafroc#59]
Hi Peter,

I am out of credits on Travis; I will need to be more careful in future on when to use the allowed credits. 

I tried installing `R` and `RStudio` on my OSX based virtual machine running Windows 8 but they failed to run.

I think I will use the `rhub` website to periodically check the software. It should work for `RJafroc` but I am not sure about `RJafrocBook`.

Maybe I should get a Windows machine? Hate to step down from the Mac.

Any ideas?

PS: their prices are atrocious: $69 per month!

**Comment by pwep** [comment]
That got used up quick!
I've been working on a GitHub Actions branch for the book but the loading takes time.
The package checking Action should be more straightforward.
I'll make a branch on my fork and get something to you.

**Comment by dpc10ster** [comment]
I saw the Action branch on GitHub - I have no idea what it does! 

Thanks.

**Comment by pwep** [comment]
Pull request #60 should help out.

The check will run with the latest release of R on Windows, Mac and Ubuntu, and the the development version of R in Ubuntu. My first test took around 30 mins to complete, but completed successfully.

<https://www.rostrum.blog/2020/08/09/ghactions-pkgs/> was helpful to get started - no need to write Actions from scratch.
The `usethis::use_github_action_check_standard()` is described in <https://usethis.r-lib.org/reference/use_github_action.html>

**Comment by dpc10ster** [comment]
Thanks for the explanations and links. Dev

**Comment by dpc10ster** [comment]
Success! 

<img width="470" alt="success" src="https://user-images.githubusercontent.com/33084612/100820773-f3444b80-341c-11eb-99f4-01cdf979f1a0.png">

Should I post a similar issue in `RJafrocBook`?

**Comment by dpc10ster** [comment]
* I am trying to get `pkgdown::build_site()` working on GitHub Actions
* This is something I have to currently do manually 
* My initial effort failed
* branch `learn_github_actions`

**Comment by pwep** [comment]
Success - the `_pkgdown.yaml` file was missing a variable name. https://github.com/dpc10ster/RJafroc/commit/72a6065028e2bcb5e2827f36b415693928b3ceb3 fixes the file in the `learn_github_actions` branch, and the website is [built and deployed](https://github.com/dpc10ster/RJafroc/runs/1502076649?check_suite_focus=true) to the `gh-pages` [branch](https://github.com/dpc10ster/RJafroc/tree/gh-pages) by the GitHub Action.

**Comment by pwep** [comment]
This sort of action should be useful for building the RJafrocBook. Is the GitHub Pages sourced from the `docs` folder in that repo? Let's open open an issue on it in RJafrocBook, like you said above.

**Comment by dpc10ster** [comment]
Yes; I will post an issue;

**Comment by dpc10ster** [comment]
I don't see some changes I made a few hours ago in `README.md` in the website at [RJafroc](https://dpc10ster.github.io/RJafroc/).

**Comment by dpc10ster** [comment]
I thought some customization I did of the `workflows/pkgdown.yaml` and the fact that I was not pushing to the `master` branch was the reason for not working. I fixed these. But, still not updating the website from current `README.md` file.

**Comment by pwep** [comment]
The master branch deployed to `gh-pages` about 40mins ago... Check the repo Settings (on the menu above, right-hand end).  Scroll down the first page of settings until you get to GitHub Pages. It might still be set to the `docs` directory in the master branch. Make sure it is set to the root of the  `gh-pages` branch.

**Comment by dpc10ster** [comment]
What is the completer URL? I changed from doc to root and got a page build failure: 

The page build failed for the `master` branch with the following error:

The variable `{{F}` on line 24 in `vignettes/Ch11Vig1SampleSize.Rmd` was not properly closed with `}}`. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#tag-not-properly-terminated <https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#tag-not-properly-terminated>.

For information on troubleshooting Jekyll see:

 https://docs.github.com/articles/troubleshooting-jekyll-builds <https://docs.github.com/articles/troubleshooting-jekyll-builds>

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=137936838&page_build_id=219323583 <https://support.github.com/contact?repo_id=137936838&page_build_id=219323583>

**Comment by dpc10ster** [comment]
got it!!!

**Comment by dpc10ster** [comment]
After any changes, in a branch different from `master` I need to merge into `master` in order to trigger a build for the website.

**Comment by dpc10ster** [comment]
I am closing this as the transition from Travis to GitHub Actions appears to be completed.

**Comment by dpc10ster** [comment]
I think I have messed up the `yaml` files; I did check using an online `yaml parser`, and the spacing/indentation seems to be OK. I was trying to add a `[skip ci]` feature as in: 

```
jobs:
  test-coverage:
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')" # the extra line to skip build
```

But it does not skip as expected with a commit message containing `[skip ci]`. And when I remove the extra line the builds don't always get activated.

**Comment by dpc10ster** [comment]
Ignore last message; I forgot about the master branch
