### ISSUE TITLE
JAFROC python version

### ISSUE THREAD

**Issue by MailSuesarn** [dpc10ster/RJafroc#71]
Hello Professor, I think you are an expert in evaluation JAFROC, I have seen a lot of resources on your github. I would like to ask if you have the JAFROC that implement in Python version?, because nowadays many AI models are built in Python, which I'm working on, so it's very convenient if an algorithm like JAFROC can be used with Python. Do you plan on developing it with Python?

Thank you so much.

**Comment by dpc10ster** [comment]
Hi, I do not know Python but am aware of its usage in the AI community (e.g., Kaggle competitions). If some one is able and willing, I can help along by providing understanding of the `RJafroc` code and its intent.
