### ISSUE TITLE
How to run R CMD checks on platforms currently not supported on rhub

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafroc#77]
the current version of `rhub` does not support several platforms that it previously did; for example, the previous version (about 2 years back) supported most of the platforms listed on [this site](https://cran.r-project.org/web/checks/check_results_RJafroc.html). The current version of `rhub` only lists 5 platforms:

```
> rhub::platforms()
macos-highsierra-release:
  macOS 10.13.6 High Sierra, R-release, brew
macos-highsierra-release-cran:
  macOS 10.13.6 High Sierra, R-release, CRAN's setup
macos-m1-bigsur-release:
  Apple Silicon (M1), macOS 11.6 Big Sur, R-release
solaris-x86-patched:
  Oracle Solaris 10, x86, 32 bit, R-release
solaris-x86-patched-ods:
  Oracle Solaris 10, x86, 32 bit, R release, Oracle Developer Studio 12.6
```

So how to check on these platforms; I have never used `docker` and dread the learning curve.

**Comment by pwep** [comment]
I have used `docker` in the past, but that will only cover the some of the linux versions you linked to. There might be something we can do with GitHub Actions which will cover the Mac and Windows build/testing.

**Comment by pwep** [comment]
A full set of platforms have returned to `rhub` (https://twitter.com/rhub_/status/1549023286465634304)

**Comment by dpc10ster** [comment]
Thank you!! I had found no reference to missing platforms in all my
previous searches

**Comment by pwep** [comment]
Some of my submissions were sat on the queue for two or three hours, before they were processed. The result email did eventually appear.

**Comment by dpc10ster** [comment]
It works; some platforms take couple of hours to complete;
