### ISSUE TITLE
rbub check failure 3 of xx: failed to failed to download dependencies readxl, testthat kableExtra 

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafroc#78]
This is output with `chk4 <- rhub::check(packagePath, platform = platforms[[1]][4])` : 

```
E  checking package dependencies (3.3s)
   Package required but not available: ‘readxl’
   
   Packages suggested but not available: 'testthat', 'kableExtra'
   
   The suggested packages are required for a complete check.
   Checking can be attempted without them by setting the environment
   variable _R_CHECK_FORCE_SUGGESTS_ to a false value.
   
   See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
   manual.
   
```

Same error with `chk4 <- rhub::check(packagePath, platform = platforms[[1]][5])` :

**Comment by pwep** [comment]
Are platforms 4 and 5 are Solaris (`solaris-x86-patched` and `solaris-x86-patched-ods`)? The CRAN check for [readxl][0], [testthat][1] and [kableExtra][2] no longer includes the results of Solaris builds.

[0]: https://cran.r-project.org/web/checks/check_results_readxl.html
[1]: https://cran.r-project.org/web/checks/check_results_testthat.html
[2]: https://cran.r-project.org/web/checks/check_results_kableExtra.html
