### ISSUE TITLE
Please review cran comments file by Sunday

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafroc#80]
Just updated Friday: This is on 8d0313c3a69ee6cf69090b58dc95dac1f20cca66. The file is `cran-comments.md`. The branch is `cran210`. 

I plan to submit to CRAN on Monday (7/25/22).

**Comment by pwep** [comment]
Looks good. I've made a pull request (#81) to update the table syntax in `cran-commends.md` so the tables render correctly in markdown preview.
No other changes to add. Compiles, tests, checks are all OK at my end.
