### ISSUE TITLE
Aesthetics of DESCRIPTION file Description field entry

### ISSUE THREAD

**Issue by dpc10ster** [dpc10ster/RJafroc#82]
Dear Peter, thanks for all your help. I am sorry if I wasted your time with the M1 platform before sidestepping it altogether. I am thinking of getting a M1 machine to replace my aging machine, and maybe I will then find out why the vignettes were creating problems.  

There is another aesthetic issue that is bugging me; while the DESCRIPTION file does not raise any flags on testing, its `Description` field converts raggedly to pdf (you will notice two almost identical parts corresponding to this field in the pdf attached: a raggedly formatted part that comes from the DESCRIPTION file and a properly formatted part which comes from `RJafroc-package.Rd`; I used `devtools::build_manual()` to make the pdf); 

The cryptic [CRAN guidance](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-structure) left me confused:

> The mandatory ‘Description’ field should give a comprehensive description of what the package does. One can use several (complete) sentences, but only one paragraph. It should be intelligible to all the intended readership (e.g. for a CRAN package to all CRAN users). It is good practice not to start with the package name, ‘This package’ or similar. As with the ‘Title’ field, double quotes should be used for quotations (including titles of books and articles), and single quotes for non-English usage, including names of other packages and external software. This field should also be used for explaining the package name if necessary. URLs should be enclosed in angle brackets, e.g. ‘<https://www.r-project.org>’: see also [Specifying URLs](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Specifying-URLs).

What do they mean by paragraph? This is an electronic document with white spaces of different types. Could you take a look at it and tell me if it can be improved (the student Xuetong Zhai who created the first version of the package put everything in one huge line, which was almost impossible to read, but which passed CRAN). 

[RJafroc_2.1.0.pdf](https://github.com/dpc10ster/RJafroc/files/9174394/RJafroc_2.1.0.pdf)

**Comment by pwep** [comment]
I have had an interesting trip into the `DESCRIPTION` file format. #83 should fix the issue, but I've not been able to check the PDF outputs. There were 4 spaces indenting the _description_ section, which meant it was treated as verbatim text (and not wrapped as expected.) In #83 have reduced the length of each line and indented using only one space.

The M1 was not a waste of time at all, at least from my end. Still no idea what is wrong, but it feels like a font rendering issue. Using a package that rendered font text as vectors made the error go away but I was not keen to introduce a new package dependency just to address an issue for one platform.

**Comment by dpc10ster** [comment]
Thanks again; issue almost fixed; I replaced the double quotes with single quotes as otherwise it does not render as expected, for example:  

> Analyzing the performance of artificial intelligence
> (AI) systems/algorithms characterized by a ``search-and-report''
> strategy. Historically, observer performance has dealt with
> 

I checked it on my platform and will repeat one windows check, just in case....

[RJafroc_2.1.0.pdf](https://github.com/dpc10ster/RJafroc/files/9174740/RJafroc_2.1.0.pdf)

**Comment by dpc10ster** [comment]
Dear maintainer,

thanks, package RJafroc_2.1.0.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Dev Chakraborty <[dpc10ster@gmail.com](mailto:dpc10ster@gmail.com)>'
