### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [dpc10ster/RJafroc#85]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that your package reaches into the internal structure of ggplot2 and those have changed in the new version.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by dpc10ster** [comment]
Thanks Thomas. I will look into it. Dev

**Comment by dpc10ster** [comment]
Hi Peter: Thanks. I have merged it
I realized that the `ggplot` structure had changed and so I regenerated the `goodValues` files which resulted in passed test on my local machine but when I pushed it to `GitHub` these tests failed. So understand your push is only testing it is a `ggplot` object and not if the plot data points agree with what I had before; if that is the case the test is less stringent; I am working on the froc book right now so I will get back to you if necessary; thanks again
Dev

**Comment by dpc10ster** [comment]
The other change I had to make was when using `geom_line()` do not use `size=` aesthetic, instead use `linewidth=`; found this when building `RJafrocFrocBook`; fortunately there is a helpful build message saying that `size` has been deprecated and giving the alternative. This does not apply to other functions like geom_point, etc.
