### ISSUE TITLE
Missing expect_known_output test in for DfBinDatasetAFROC (test-data-file.R)

### ISSUE THREAD

**Issue by pwep** [dpc10ster/RJafroc#9]
The following test creates a new tempfile of output, but does not repeat DfBinDatasetAFROC to compare.

https://github.com/dpc10ster/RJafroc/blob/8c0602ff19772770fdea1029ce65ce82e050fb2e/tests/testthat/test-data-file.R#L83-L88

**Comment by pwep** [comment]
Alternatively, is that the intention of the test? Just to check that the data is generated once and the file produced without errors? (rather than produce it twice, and compare the outputs)

I have found other test files where a new tempfile name is created, but only written to once using `expect_known_output`.

- tests/testthat/test-StSignificanceTestingCad.R
- tests/testthat/test-datasets.R

**Comment by dpc10ster** [comment]
I am going to close this issue as your fix takes care of these spurious warnings. Thank you Peter.
