### ISSUE TITLE
Statistics Question

### ISSUE THREAD

**Issue by vanhoesens** [dpc10ster/RJafroc#92]
I am a relatively new user with R (using RStudio) and I am using this package for a medical image reconstruction study. The study is forced mark LROC and all of the code is working fine. My question is about the statistics of the calculations made in the code. I am using PlotEmpiricalOperatingCharacteristics and I noticed that it calls multiple levels of functions that cannot be directly accessed in the package. I know they can be found with 'getAnywhere' but these functions do not have documentation or much commenting.
When I plot LROC data with floating point scores, how is the program binning that data? I am getting a step function graph so I know that there is some binning but I have not been able to track down exactly how that is decided.
Thanks,
Sarah

**Comment by dpc10ster** [comment]
I am retired and have transferred maintenance of this package to @pwep (Peter Philips). Plotting is done via the `ggplot2` package which has its own documentation (this widely used package is very code-dense, and I don't pretend to understand it - I just use it). `RJafroc` is NOT binning the data as empirical plots used the raw data. I suggest testing `RJafroc` with a small dataset (one reader, one modality and a few cases) and plot the LROC data manually and compare your plot (and AUC) to what the program is giving. If there is a discrepancy you should post an issue documenting your finding.
